# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/docs/sushi/configuration/                    │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: kindlab.fhir.mimic
canonical: http://mimic.mit.edu/fhir/mimic
name: MIMIC
title: MIMIC Implementation Guide
status: draft
version: 1.3.0
fhirVersion: 4.0.1
copyrightYear: 2022+
releaseLabel: Draft
publisher:
  name: KinD Lab
  url: http://fhir.kindlab.sickkids.ca

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided input/includes/menu.xml file, delete the "menu" property below.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  Home: index.html
  Background:
    General Background: index.html
    MIMIC-IV Mapping: mimic-fhir-mappings.html
    MIMIC-ED Mapping: mimic-ed-fhir-mappings.html
  Guidance:
    General: guidance.html
    Terminology: terminology-guide.html
    Applications: applications.html
    Tutorials: tutorials.html
    Future Work: future-work.html
  Subsets:
    Microbiology data: microbiology-background.html
    Medication data: medication-background.html
    Emergency Department data: emergency-department-subset.html
    Intensive Care Unit data: intensive-care-unit-subset.html    
  Artifacts: artifacts.html
  Examples: artifacts.html#example-example-instances
  Downloads: downloads.html
  Change Log: changelog.html

pages:
  index.md:
  mimic-fhir-mappings.md:
    mimic-ed-fhir-mappings.md:
  guidance.md:
    terminology-guide.md:
    applications.md:
    tutorials.md:
    future-work.md:
  microbiology-background.md:
    medication-background.md:
    emergency-department-subset.md:
    intensive-care-unit-subset.md:
  downloads.md:
  changelog.md:  
